-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bank_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  item_id text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  category text NOT NULL DEFAULT 'material'::text,
  rarity text DEFAULT 'common'::text,
  slot_position integer CHECK (slot_position >= 0 AND slot_position < 200),
  is_pinned boolean DEFAULT false,
  pinned_at timestamp with time zone,
  stored_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_items_pkey PRIMARY KEY (id),
  CONSTRAINT bank_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT bank_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.bank_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  transaction_type text NOT NULL,
  item_id text,
  quantity_moved integer,
  category text,
  gem_cost integer,
  gems_before integer,
  gems_after integer,
  slots_before integer,
  slots_after integer,
  success boolean DEFAULT true,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT bank_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel text NOT NULL,
  sender_id uuid,
  receiver_id uuid,
  guild_id uuid,
  content text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_by uuid,
  flagged boolean DEFAULT false,
  flagged_reason text,
  deleted_at timestamp without time zone,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.craft_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  recipe_id uuid NOT NULL,
  batch_count integer NOT NULL DEFAULT 1,
  started_at timestamp with time zone DEFAULT now(),
  completes_at timestamp with time zone NOT NULL,
  is_completed boolean DEFAULT false,
  claimed boolean DEFAULT false,
  failed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT craft_queue_pkey PRIMARY KEY (id),
  CONSTRAINT craft_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT craft_queue_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.crafting_recipes(id)
);
CREATE TABLE public.crafted_items_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  item_id text NOT NULL,
  quantity integer NOT NULL,
  rarity character varying NOT NULL,
  facility_id uuid,
  recipe_id text,
  enhancement_level integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT crafted_items_log_pkey PRIMARY KEY (id),
  CONSTRAINT crafted_items_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT crafted_items_log_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.crafting_recipes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  output_item_id text NOT NULL,
  required_level integer NOT NULL DEFAULT 1,
  production_time_seconds integer NOT NULL,
  success_rate double precision NOT NULL DEFAULT 0.8,
  xp_reward integer NOT NULL DEFAULT 0,
  ingredients jsonb NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT crafting_recipes_pkey PRIMARY KEY (id),
  CONSTRAINT crafting_recipes_output_item_id_fkey FOREIGN KEY (output_item_id) REFERENCES public.items(id)
);
CREATE TABLE public.facilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  level integer NOT NULL DEFAULT 1,
  suspicion_level integer NOT NULL DEFAULT 0 CHECK (suspicion_level >= 0 AND suspicion_level <= 100),
  is_active boolean DEFAULT true,
  production_started_at timestamp with time zone,
  last_production_collected_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  offline_production_cap integer DEFAULT 0,
  workers integer DEFAULT 0,
  is_unlocked boolean DEFAULT true,
  last_production timestamp with time zone,
  CONSTRAINT facilities_pkey PRIMARY KEY (id),
  CONSTRAINT facilities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.facility_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  recipe_id text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  started_at bigint NOT NULL,
  completed_at bigint NOT NULL,
  status text DEFAULT 'in_progress'::text,
  is_raided boolean DEFAULT false,
  is_burned boolean DEFAULT false,
  rarity_outcome character varying,
  collected boolean NOT NULL DEFAULT false,
  collected_at timestamp without time zone,
  failed boolean NOT NULL DEFAULT false,
  failure_reason character varying,
  created_at timestamp without time zone DEFAULT now(),
  estimated_completion_at timestamp without time zone,
  duration_seconds integer,
  CONSTRAINT facility_queue_pkey PRIMARY KEY (id),
  CONSTRAINT facility_queue_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT facility_queue_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.facility_recipes(id)
);
CREATE TABLE public.facility_recipes (
  id text NOT NULL,
  facility_type text NOT NULL,
  output_item_id text NOT NULL,
  output_quantity integer NOT NULL DEFAULT 1,
  input_materials jsonb DEFAULT '{}'::jsonb,
  gold_cost integer DEFAULT 0,
  duration_seconds integer NOT NULL,
  required_level integer DEFAULT 1,
  success_rate integer DEFAULT 100,
  base_suspicion_increase integer DEFAULT 0,
  production_speed_bonus double precision DEFAULT 1.0,
  rarity_distribution jsonb DEFAULT '{"EPIC": 1.5, "RARE": 8, "COMMON": 70, "UNCOMMON": 20, "LEGENDARY": 0.5}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  min_facility_level integer DEFAULT 1,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT facility_recipes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.guild_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id uuid,
  activity_type text,
  user_id uuid,
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guild_activities_pkey PRIMARY KEY (id),
  CONSTRAINT guild_activities_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES public.guilds(id)
);
CREATE TABLE public.guild_wars (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_1_id uuid,
  guild_2_id uuid,
  guild_1_points integer DEFAULT 0,
  guild_2_points integer DEFAULT 0,
  winner_guild_id uuid,
  start_time timestamp without time zone,
  end_time timestamp without time zone,
  status text DEFAULT 'upcoming'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guild_wars_pkey PRIMARY KEY (id),
  CONSTRAINT guild_wars_guild_1_id_fkey FOREIGN KEY (guild_1_id) REFERENCES public.guilds(id),
  CONSTRAINT guild_wars_guild_2_id_fkey FOREIGN KEY (guild_2_id) REFERENCES public.guilds(id),
  CONSTRAINT guild_wars_winner_guild_id_fkey FOREIGN KEY (winner_guild_id) REFERENCES public.guilds(id)
);
CREATE TABLE public.guilds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  tag text NOT NULL UNIQUE,
  description text,
  logo_url text,
  founder_id uuid,
  leader_id uuid,
  member_count integer DEFAULT 1,
  max_members integer DEFAULT 50,
  level integer DEFAULT 1,
  xp bigint DEFAULT 0,
  treasury_gold bigint DEFAULT 0,
  tax_rate numeric DEFAULT 0.05,
  season_points integer DEFAULT 0,
  is_recruiting boolean DEFAULT true,
  min_level_requirement integer DEFAULT 1,
  min_level integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guilds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hospital_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  reason text,
  related_battle_id uuid,
  duration_minutes integer NOT NULL,
  release_time timestamp without time zone NOT NULL DEFAULT (now() + '00:30:00'::interval),
  early_release boolean DEFAULT false,
  early_release_gem_cost integer,
  early_release_time timestamp without time zone,
  admitted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hospital_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory (
  row_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  item_id text NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  slot_position integer,
  is_equipped boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  equip_slot text,
  description text,
  icon text,
  weapon_type text,
  armor_type text,
  material_type text,
  potion_type text,
  base_price integer DEFAULT 0,
  vendor_sell_price integer DEFAULT 0,
  is_tradeable boolean DEFAULT true,
  is_stackable boolean DEFAULT true,
  max_stack integer DEFAULT 999,
  max_enhancement integer DEFAULT 0,
  can_enhance boolean DEFAULT false,
  heal_amount integer DEFAULT 0,
  tolerance_increase integer DEFAULT 0,
  overdose_risk double precision DEFAULT 0.0,
  required_level integer DEFAULT 0,
  required_class text,
  recipe_requirements jsonb DEFAULT '{}'::jsonb,
  recipe_result_item_id text,
  recipe_building_type text,
  recipe_production_time integer DEFAULT 0,
  recipe_required_level integer DEFAULT 0,
  rune_enhancement_type text,
  rune_success_bonus double precision DEFAULT 0.0,
  rune_destruction_reduction double precision DEFAULT 0.0,
  cosmetic_effect text,
  cosmetic_bind_on_pickup boolean DEFAULT false,
  cosmetic_showcase_only boolean DEFAULT false,
  production_building_type text,
  production_rate_per_hour integer DEFAULT 0,
  production_required_level integer DEFAULT 0,
  bound_to_player boolean DEFAULT false,
  pending_sync boolean DEFAULT false,
  enhancement_level integer DEFAULT 0,
  obtained_at bigint,
  is_favorite boolean DEFAULT false,
  CONSTRAINT inventory_pkey PRIMARY KEY (row_id),
  CONSTRAINT inventory_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.items (
  id text NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  description text,
  rarity text DEFAULT 'common'::text,
  icon text,
  base_price integer DEFAULT 0,
  vendor_sell_price integer DEFAULT 0,
  is_tradeable boolean DEFAULT true,
  is_stackable boolean DEFAULT true,
  max_stack integer DEFAULT 999,
  created_at timestamp with time zone DEFAULT now(),
  equip_slot text,
  weapon_type text,
  armor_type text,
  material_type text,
  potion_type text,
  attack integer DEFAULT 0,
  defense integer DEFAULT 0,
  health integer DEFAULT 0,
  power integer DEFAULT 0,
  energy_restore integer DEFAULT 0,
  heal_amount integer DEFAULT 0,
  can_enhance boolean DEFAULT false,
  max_enhancement integer DEFAULT 0,
  required_level integer DEFAULT 1,
  required_class text,
  tolerance_increase integer DEFAULT 0,
  overdose_risk numeric DEFAULT 0,
  production_building_type text,
  rune_enhancement_type text,
  rune_success_bonus double precision DEFAULT 0.0,
  rune_destruction_reduction double precision DEFAULT 0.0,
  health_restore integer DEFAULT 0,
  mana_restore integer DEFAULT 0,
  buff_duration integer DEFAULT 0,
  production_rate_per_hour integer DEFAULT 0,
  production_required_level integer DEFAULT 0,
  recipe_requirements jsonb DEFAULT '{}'::jsonb,
  recipe_result_item_id text,
  recipe_building_type text,
  recipe_production_time integer DEFAULT 0,
  recipe_required_level integer DEFAULT 0,
  cosmetic_effect text,
  cosmetic_bind_on_pickup boolean DEFAULT false,
  cosmetic_showcase_only boolean DEFAULT false,
  updated_at timestamp without time zone DEFAULT now(),
  craftable boolean DEFAULT false,
  craft_time_seconds integer,
  shop_available boolean NOT NULL DEFAULT true,
  shop_currency text NOT NULL DEFAULT 'gold'::text CHECK (shop_currency = ANY (ARRAY['gold'::text, 'gems'::text])),
  CONSTRAINT items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.market_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id text NOT NULL,
  seller_id uuid NOT NULL,
  buyer_id uuid NOT NULL,
  quantity integer NOT NULL,
  price integer NOT NULL,
  total_price integer,
  market_fee integer,
  sold_at timestamp with time zone DEFAULT now(),
  CONSTRAINT market_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.market_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  item_id text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  price integer NOT NULL CHECK (price >= 0),
  region_id integer DEFAULT 1,
  listed_at bigint DEFAULT (EXTRACT(epoch FROM now()))::bigint,
  item_data jsonb DEFAULT '{}'::jsonb,
  buyer_id uuid,
  total_price integer,
  status text DEFAULT 'active'::text,
  sold_at bigint,
  expires_at bigint,
  updated_at timestamp with time zone DEFAULT now(),
  currency text NOT NULL DEFAULT 'gold'::text CHECK (currency = 'gold'::text),
  CONSTRAINT market_orders_pkey PRIMARY KEY (id),
  CONSTRAINT market_orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id)
);
CREATE TABLE public.prison_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  facility_id uuid,
  reason character varying NOT NULL,
  sentence_hours integer NOT NULL,
  admitted_at timestamp without time zone DEFAULT now(),
  released_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT prison_records_pkey PRIMARY KEY (id),
  CONSTRAINT prison_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT prison_records_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.production_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  facility_id uuid NOT NULL,
  recipe_id uuid NOT NULL,
  status text DEFAULT 'queued'::text,
  started_at timestamp without time zone,
  completed_at timestamp without time zone,
  estimated_completion_at timestamp without time zone,
  success boolean,
  result_item_id text,
  batch_number integer DEFAULT 1,
  sequence_order integer,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT production_queue_pkey PRIMARY KEY (id),
  CONSTRAINT production_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT production_queue_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT production_queue_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.crafting_recipes(id)
);
CREATE TABLE public.pvp_battles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attacker_id uuid,
  defender_id uuid,
  attacker_power integer,
  defender_power integer,
  attacker_energy_before integer,
  outcome text,
  winner_id uuid,
  gold_stolen integer DEFAULT 0,
  attacker_hospital_minutes integer DEFAULT 0,
  defender_hospital_minutes integer DEFAULT 0,
  attacker_energy_cost integer DEFAULT 0,
  rating_change_attacker integer DEFAULT 0,
  rating_change_defender integer DEFAULT 0,
  battled_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pvp_battles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_bank_account (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  total_slots integer NOT NULL DEFAULT 100 CHECK (total_slots >= 100 AND total_slots <= 200),
  used_slots integer NOT NULL DEFAULT 0,
  free_slots_remaining integer NOT NULL DEFAULT 100,
  paid_slots_purchased integer NOT NULL DEFAULT 0,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_bank_account_pkey PRIMARY KEY (id),
  CONSTRAINT user_bank_account_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_id uuid UNIQUE,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  display_name text,
  avatar_url text,
  level integer DEFAULT 1,
  xp integer DEFAULT 0,
  gold integer DEFAULT 1000,
  energy integer DEFAULT 100,
  max_energy integer DEFAULT 100,
  energy_last_updated timestamp with time zone DEFAULT now(),
  attack integer DEFAULT 10,
  defense integer DEFAULT 10,
  health integer DEFAULT 100,
  max_health integer DEFAULT 100,
  power integer DEFAULT 0,
  is_online boolean DEFAULT false,
  is_banned boolean DEFAULT false,
  ban_reason text,
  banned_until timestamp with time zone,
  tutorial_completed boolean DEFAULT false,
  last_daily_reward timestamp with time zone,
  total_playtime_seconds integer DEFAULT 0,
  guild_id uuid,
  guild_role text,
  referral_code text UNIQUE,
  referred_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone DEFAULT now(),
  gems integer DEFAULT 100,
  experience integer DEFAULT 0,
  addiction_level integer DEFAULT 0,
  tolerance integer DEFAULT 0,
  in_hospital boolean DEFAULT false,
  hospital_until timestamp without time zone,
  hospital_reason text,
  in_prison boolean DEFAULT false,
  prison_until timestamp with time zone,
  prison_reason text,
  pvp_wins integer DEFAULT 0,
  pvp_losses integer DEFAULT 0,
  pvp_rating integer DEFAULT 1000,
  reputation integer DEFAULT 0,
  global_suspicion_level integer NOT NULL DEFAULT 0 CHECK (global_suspicion_level >= 0 AND global_suspicion_level <= 100),
  risk_baseline double precision DEFAULT 0,
  last_bribe_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id),
  CONSTRAINT users_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.users(id)
);