-- =========================================================================================
-- MIGRATION: Fix Dungeon Data RPC + Loot Drops — SUPERSEDED
-- =========================================================================================
-- ⛔ SUPERSEDED — This file shares timestamp 20260312_010000 with
-- 20260312_010000_dungeon_fixes.sql which is the canonical version.
--
-- 20260312_010000_dungeon_fixes.sql includes:
--   • get_dungeons() with zone / zone_name / dungeon_order / is_boss fields
--     required by the frontend DungeonData type contract.
--   • enter_dungeon() with full loot-drop logic (loot_rarity_weights, inventory insert).
--   • NULL-safe pvp_attack patch.
--
-- This file's original get_dungeons() definition OMITS those fields and would break
-- the frontend if applied after dungeon_fixes.sql.
-- This file is intentionally left as a no-op to preserve Supabase migration history.
-- =========================================================================================
